# -*- coding: utf-8 -*-
"""Ulepszony Moduł Utils

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ir-NLW2-gTdE4h426MJkfSkhsTovCdAz
"""

"""
Moduł z funkcjami pomocniczymi, używanymi przez różnych agentów.
"""
# Ulepszono: Dodano type hinting.
from typing import Any, Dict, Optional, Union

def get_latest_value(data: Optional[Dict], primary_key: str, secondary_key: Optional[str] = None) -> Any:
    """
    Bezpiecznie pobiera najnowszą wartość z danych szeregów czasowych Alpha Vantage.
    """
    if not data or primary_key not in data:
        return None

    time_series = data.get(primary_key)
    # Ulepszono: Sprawdza, czy time_series jest słownikiem i nie jest pusty.
    if not isinstance(time_series, dict) or not time_series:
        return None

    try:
        # Pobiera pierwszy klucz (najnowszą datę) ze słownika.
        latest_date = next(iter(time_series))
        latest_data = time_series[latest_date]
    except (StopIteration, KeyError):
        return None

    if secondary_key:
        return latest_data.get(secondary_key)
    return latest_data

def safe_float(value: Any, default: float = 0.0) -> float:
    """
    Bezpiecznie konwertuje wartość na float, obsługując None i błędy.
    """
    if value is None:
        return default
    try:
        return float(value)
    except (ValueError, TypeError):
        return default